//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "nanoFramework_Hardware_Esp32_RMT.h"

using nfesp32RMT = Library_nanoFramework_Hardware_Esp32_RMT_nanoFramework_Hardware_Esp32_RMT_Transmitter;

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    nfesp32RMT::NativeDispose___STATIC__VOID__I4,
    nfesp32RMT::NativeGetClockDiv___STATIC__U1__I4,
    nfesp32RMT::NativeGetTransmitIdleLevel___STATIC__BOOLEAN__I4,
    nfesp32RMT::NativeInit___STATIC__I4__I4,
    nfesp32RMT::NativeIsSource80MHz___STATIC__BOOLEAN__I4,
    nfesp32RMT::NativeIsTransmitIdleEnabled___STATIC__BOOLEAN__I4,
    nfesp32RMT::NativeSendData___STATIC__VOID__I4__SZARRAY_U1,
    nfesp32RMT::NativeSetCarierMode___STATIC__VOID__I4__BOOLEAN__U2__U2__BOOLEAN,
    nfesp32RMT::NativeSetClockDiv___STATIC__VOID__I4__U1,
    nfesp32RMT::NativeSetSource80MHz___STATIC__VOID__I4__BOOLEAN,
    nfesp32RMT::NativeSetTransmitIdleEnabled___STATIC__VOID__I4__BOOLEAN,
    nfesp32RMT::NativeSetTransmitIdleLevel___STATIC__VOID__I4__BOOLEAN,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_nanoFramework_Hardware_Esp32_RMT =
{
    "nanoFramework.Hardware.Esp32.RMT", 
    0x34A0F401,
    method_lookup,
    ////////////////////////////////////////////////////////////////////////////////////
    // check if the version bellow matches the one in AssemblyNativeVersion attribute //
    ////////////////////////////////////////////////////////////////////////////////////
    { 1, 0, 0, 0 }
};
