//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "nanoFramework_Hardware_Esp32_RMT.h"
#include "PulseCommand.h"

using namespace nanoFramework::Hardware::Esp32::RMT::Tx;


HRESULT Library_nanoFramework_Hardware_Esp32_RMT_nanoFramework_Hardware_Esp32_RMT_Tx_PulseCommand::SerialiseTo___STATIC__VOID__SZARRAY_U1__I4__U2__U2__BOOLEAN__BOOLEAN( CLR_RT_StackFrame& stack )
{
    NANOCLR_HEADER(); hr = S_OK;
    {
        CLR_RT_TypedArray_UINT8 param0;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT8_ARRAY( stack, 0, param0 ) );

        signed int param1;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_INT32( stack, 1, param1 ) );

        unsigned short param2 = stack.ArgN( 2 ).NumericByRef().u2;
        //NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT16( stack, 2, param2 ) );

        unsigned short param3 = stack.ArgN( 3 ).NumericByRef().u2;
        //NANOCLR_CHECK_HRESULT( Interop_Marshal_UINT16( stack, 3, param3 ) );

        bool param4;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_bool( stack, 4, param4 ) );

        bool param5;
        NANOCLR_CHECK_HRESULT( Interop_Marshal_bool( stack, 5, param5 ) );

        PulseCommand::SerialiseTo( param0, param1, param2, param3, param4, param5, hr );
        NANOCLR_CHECK_HRESULT( hr );
    }
    NANOCLR_NOCLEANUP();
}
